### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ivan-pavlovic**
You should merge this into develop (of course that branch must be created first)

### CODE REVIEW

**Comment by emiltin** [comment]
closed?

**Comment by ivan-pavlovic** [comment]
Yes. The repo was removed.

**Comment by emiltin** [comment]
I don't understand. Do you still want me to merge the changes to a develop branch in our repo?

**Comment by ivan-pavlovic** [comment]
No need to. Since there were no changes after I made the fork it will be easier just to transfer the repo.

**Comment by emiltin** [comment]
but the relevant changes are in the develop branch of you forked repo?

**Comment by ivan-pavlovic** [comment]
Yes. I just did the same as for ibikecph. Everything is in develop branch, all projects included as submodules.

**Comment by emiltin** [comment]
i don't see you cykeplanen-ios-legacy repo anymore?

**Comment by emiltin** [comment]
if i add a develop branch to our repos, can you just send a PR?

**Comment by ivan-pavlovic** [comment]
The repo has been removed. After you add a develop branch I will create a PR for the proper branch. Of course, I will have to transfer the repo back to GitHub but you’ll have to talk to Frederik about that.

**Comment by emiltin** [comment]
i've added develop branch. will you send a PR or do you mean that something has to be cleared with frederik first?

**Pull request closed without merging**
